### ISSUE TITLE
[BUG] Hydra nao esta baixando nenhum jogo nem verificandoa rquivos

### ISSUE THREAD

**Issue by renasc1994** [hydralauncher/hydra#1059]
### Describe the bug

Fiquei algum tempo sem usar, agora que fui usar, está atualziado, mas nao esta baixando os torrents e nem verificando os arquivos dos torrents que estavam sendo baixados

### Steps to Reproduce

1. initiate the app
2. star or resume any downloads
3. dont work

### Expected behavior

1. to work

### Additional information and data

[error.old.txt](https://github.com/user-attachments/files/17351592/error.old.txt)
[error.txt](https://github.com/user-attachments/files/17351593/error.txt)
[info.txt](https://github.com/user-attachments/files/17351594/info.txt)
[logs.txt](https://github.com/user-attachments/files/17351595/logs.txt)
[pythoninstance.txt](https://github.com/user-attachments/files/17351596/pythoninstance.txt)

### Operating System

Windows 11

### Hydra Version

2.1.7

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by ereh7** [comment]
o meu tambem

**Comment by HeitorAugustoLN** [comment]
Mesma coisa quando rodando pelo NixOS

**Comment by zamitto** [comment]
@renasc1994 looking into your logs it's possible to see you are trying to download inside the root of your E: drive. 
Could you try to select a folder that is 100% sure to have write permission? Like you user Downloads folder?

**Comment by renasc1994** [comment]
> @renasc1994 looking into your logs it's possible to see you are trying to download inside the root of your E: drive. Could you try to select a folder that is 100% sure to have write permission? Like you user Downloads folder?

sure, i cant try it now, but i will as soon as i can and post results here.

But i need to say that i never changed the downlaod location, its the same as always, and i downlaod a few dozens of games there.

**Comment by HeitorAugustoLN** [comment]
> @renasc1994 looking into your logs it's possible to see you are trying to download inside the root of your E: drive. Could you try to select a folder that is 100% sure to have write permission? Like you user Downloads folder?

```
12:35:31.250                   › Unhandled rejection TypeError: Cannot read properties of undefined (reading 'rpc')
    at handleRpcError (file:///nix/store/2lgvanzblivmxps05zyqys5zf61nfcwy-hydralauncher-2.1.7/libexec/Hydra/resources/app.asar/out/main/index.js:1333:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PythonInstance.startDownload (file:///nix/store/2lgvanzblivmxps05zyqys5zf61nfcwy-hydralauncher-2.1.7/libexec/Hydra/resources/app.asar/out/main/index.js:1311:13)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'rpc')
    at handleRpcError (file:///nix/store/2lgvanzblivmxps05zyqys5zf61nfcwy-hydralauncher-2.1.7/libexec/Hydra/resources/app.asar/out/main/index.js:1333:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PythonInstance.startDownload (file:///nix/store/2lgvanzblivmxps05zyqys5zf61nfcwy-hydralauncher-2.1.7/libexec/Hydra/resources/app.asar/out/main/index.js:1311:13)
```

I'm running into this issue when running in NixOS, with the package I created
