### ISSUE TITLE
Hydra doesn't download any game

### ISSUE THREAD

**Issue by chrisbewz** [hydralauncher/hydra#188]
After installing hydra as recommended and all necessary tools (Node, yarn), I tried to download some games but the download event starts and my terminal displays below message:

```bash

Error occurred in handler for 'startGameDownload': TypeError: Cannot read properties of undefined (reading 'id')
    at getSteamGameIconUrl (file:///C:/Users/chris/hydra/out/main/index-D8hLsHkD.js:64:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startGameDownload (file:///C:/Users/chris/hydra/out/main/index-D8hLsHkD.js:821:45)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:77963)

```

Also the infos contained on *error* file:

```json

{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}
{"level":"error","message":"Cannot read properties of undefined (reading 'textContent')","method":"getNewRepacksFromCPG"}


```

Whatever the game i choose to install the above error occurs.

Context:

OS: Windows 11 23H2 22631.3447
Hydra version: 1.1.1

Whatever the game i choose to install the above error occurs.

**Comment by zamitto** [comment]
If you want to just use Hydra you can download it from the [Releases page](https://github.com/hydralauncher/hydra/releases)

You need to follow the README instructions only if you want to contribute to the code

**Comment by FelipeHCS0055** [comment]
https://www.reddit.com/r/hydralauncher/comments/1dpngtd/no_downloads_available/
