### ISSUE TITLE
[BUG]  Json Decoder error when importing json

### ISSUE THREAD

**Issue by nonunknown777** [hydralauncher/hydra#773]
### Describe the bug

When you import the json from cloud the following error happens:

```
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/threading.py", line 980, in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/threading.py", line 917, in run
  File "torrent-client/main.py", line 85, in listen_to_socket
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 346, in loads
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 337, in decode
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

### Steps to Reproduce

Open Hydra on linux, Settings -> Download Sources -> Add Source -> Inser json link

### Expected behavior

Expected to be able to download the games

### Operating System

Big LInux

### Hydra Version

2.0.2 Leviticus

**Comment by zamitto** [comment]
@nonunknown777, does it still happen in 2.1.7?

**Comment by JackEnx** [comment]
long time without response, if the problem persists, open the issue again.
