### ISSUE TITLE
[BUG] Write a title for your bug

### ISSUE THREAD

**Issue by profucius** [hydralauncher/hydra#990]
### Describe the bug

UI loads fine in v2.0.3 but fails to display anything on Home screen on 2.1.1 and later.

# v2.0.3 displaying games on home screen fine
![image](https://github.com/user-attachments/assets/df92ce6e-3a1b-465f-90ed-b39af0cdb63b)

# v2.1.1 (same for any version after) display nothing on the home screen.
Search also does NOT work.
![image](https://github.com/user-attachments/assets/2cf9b3f2-f0df-46a1-b00e-08bf495576db)
![image](https://github.com/user-attachments/assets/83eed9d3-a040-4efb-b599-954dd27f1444)

# Error log attached here:
Will self-delete in one month from this post date: https://pastebin.com/wxipLjyX
It mentions "ERR_FR_TOO_MANY_REDIRECTS" but perhaps there is a deeper issue?

Below is the brief output in the `info.txt` file
```
[2024-09-18 14:43:34.745] [info]  (main)            Migrations failed to run: Error: The migration directory is corrupt, the following files are missing: EnsureRepackUris, FixMissingColumns
    at validateMigrationList (D:\Temp\2m5aMAQK3PqdsX6dBKBi5iBMMD7\resources\app.asar\node_modules\knex\lib\migrations\migrate\Migrator.js:567:11)
    at Migrator.list (D:\Temp\2m5aMAQK3PqdsX6dBKBi5iBMMD7\resources\app.asar\node_modules\knex\lib\migrations\migrate\Migrator.js:285:7)
    at async runMigrations (file:///D:/Temp/2m5aMAQK3PqdsX6dBKBi5iBMMD7/resources/app.asar/out/main/index.js:7077:3)
    at async file:///D:/Temp/2m5aMAQK3PqdsX6dBKBi5iBMMD7/resources/app.asar/out/main/index.js:7089:3
[2024-09-18 14:43:35.517] [info]  (main)            Checking for update
[2024-09-18 14:43:35.520] [info]  (main)             ---- REQUEST -----
[2024-09-18 14:43:35.521] [info]  (main)            get /games/trending { language: 'en-US' } undefined
[2024-09-18 14:43:35.544] [info]  (main)             ---- REQUEST -----
[2024-09-18 14:43:35.545] [info]  (main)            get /games/hot?take=12&skip=0 {} undefined
```

### Steps to Reproduce

Download portable version of 2.0.3 and run it. `hydra.db` already exists so the settings prevail.
Then download portable version 2.1.1 and run it. Since `hydra.db` exists it should display games on home screen.

### Expected behavior

Games to display on home screen, and searches to work, etc.

### Operating System

Windows 11 24H2

### Hydra Version

2.1.1 and later

### Before opening this Issue

- [X] I have searched the issues of this repository and believe that this is not a duplicate.
- [X] I am aware that Hydra team does not offer any support or help regarding the downloaded games.

**Comment by zamitto** [comment]
The pastebin is not loading for me.
 Search, Hot games and Games of the week load from our API, the ERR_FR_TOO_MANY_REDIRECTS you mentioned could be related to your issue. But first try doing the above and if the issue persists, upload your logs again

**Comment by profucius** [comment]
Thanks, the solution was to delete and recreate the hydra.db file on 2.1.5. I don't think I launched an older version after, but at this point it's difficult to say. I'll close ticket now, thanks again
